export const cartData = [
  {
    id: 1,
    name: "라틀리에 후르츠아가빈 에어팟프로케이스",
    model: "무화과",
    select: { design: "무화과" },
    price: "₩12,000",
    img: "https://akan.co.kr/upload/products/AIRPRO/LATR5004/thumb1906.jpg",
  },
  {
    id: 2,
    name: "나만의 커스텀 맥세이프 카드케이스",
    model: "아이폰16플러스",
    select: "",
    price: "₩25,000",
    select: "",
    img: "https://akan.co.kr/upload/products/MDBUMP/AQ9999/thumb-single-graybg.webp",
  },
  {
    id: 3,
    name: "양궁대회 커스텀 방탄케이스",
    model: "아이폰14PRO",
    price: "₩10,000",
    select: "",
    img: "https://akan.co.kr/upload/products/NEVER/NWKN0001/thumb-single-graybg.webp",
  },
  {
    id: 4,
    name: "늘어지냥 커스텀 방탄케이스",
    model: "아이폰16플러스",
    price: "₩20,000",
    select: "",
    img: "https://akan.co.kr/upload/products/NEVER/KYJN5004/thumb-single-graybg.webp",
  },
];
