export const userData = [
  {
    userId: 1,
    id: "hataraci9350",
    pwd: 1234,
    carts: [
      {
        cartId: 1,
        productId: 1,
        id: "hataraci9350",
        name: "나만의 커스텀 방탄케이스",
        quantity: 4,
        singlePrice: 9000,
        image:
          "https://akan.co.kr/upload/products/NEVER/AN9999/thumb-single-graybg.webp",
      },
      {
        cartId: 2,
        productId: 2,
        id: "hataraci9350",
        name: "그려용 커스텀 방탄케이스",
        quantity: 2,
        singlePrice: 10000,
        img: "https://akan.co.kr/upload/products/NEVER/KN0284/thumb-single-graybg.webp",
      },
      {
        cartId: 3,
        productId: 121,
        id: "hataraci9350",
        name: "노을토끼 맥세이프 커스텀 카드지갑",
        quantity: 1,
        singlePrice: 15000,
        image:
          "https://akan.co.kr/upload/products/MPOCKET/ZSEY5232/thumb-single-graybg.webp",
      },
    ],
    reviews: [
      {
        reviewId: 1,
        productId: 1,
        id: "hataraci9350",
        title: "제품 좋아요",
        detail: "제품 좋은것같아요",
        date: "2025. 9. 3. 오후 2:09:55",
      },
      {
        reviewId: 2,
        productId: 2,
        id: "hataraci9350",
        title: "제품 구려요",
        detail: "구리다 구려",
        date: "2025. 9. 3. 오후 2:10:55",
      },
      {
        reviewId: 3,
        productId: 2,
        id: "hataraci9350",
        title: "망해라",
        detail: "제품 구리다 진짜 망해라",
        date: "2025. 9. 3. 오후 2:11:55",
      },
    ],
  },
  {
    userId: 2,
    id: "sora1228",
    pwd: 1234,
    carts: [
      {
        cartId: 4,
        productId: 1,
        id: "sora1228",
        name: "나만의 커스텀 방탄케이스",
        quantity: 1,
        singlePrice: 9000,
        image:
          "https://akan.co.kr/upload/products/NEVER/AN9999/thumb-single-graybg.webp",
      },
      {
        cartId: 5,
        productId: 2,
        id: "sora1228",
        name: "그려용 커스텀 방탄케이스",
        quantity: 2,
        singlePrice: 10000,
        img: "https://akan.co.kr/upload/products/NEVER/KN0284/thumb-single-graybg.webp",
      },
    ],
    reviews: [
      {
        reviewId: 4,
        productId: 1,
        id: "sora1228",
        title: "제품 구려요",
        detail: "구리다 구려",
        date: "2025. 9. 3. 오후 1:09:55",
      },
      {
        reviewId: 5,
        productId: 2,
        id: "sora1228",
        title: "망해라",
        detail: "제품 구리다 진짜 망해라",
        date: "2025. 9. 3. 오후 1:10:55",
      },
    ],
  },
  { userId: 3, id: "dbfk", pwd: 1234, carts: [], reviews: [] },
  {
    userId: 4,
    id: "bk",
    pwd: 1234,
    carts: [
      {
        cartId: 1,
        productId: 1,
        id: "bk",
        name: "나만의 커스텀 방탄케이스",
        quantity: 1,
        singlePrice: 9000,
        image:
          "https://akan.co.kr/upload/products/NEVER/AN9999/thumb-single-graybg.webp",
      },
      {
        cartId: 2,
        productId: 2,
        id: "bk",
        name: "그려용 커스텀 방탄케이스",
        quantity: 2,
        singlePrice: 10000,
        img: "https://akan.co.kr/upload/products/NEVER/KN0284/thumb-single-graybg.webp",
      },
      {
        cartId: 3,
        productId: 121,
        id: "bk",
        name: "노을토끼 맥세이프 커스텀 카드지갑",
        quantity: 3,
        singlePrice: 15000,
        image:
          "https://akan.co.kr/upload/products/MPOCKET/ZSEY5232/thumb-single-graybg.webp",
      },
    ],
    reviews: [
      {
        reviewId: 6,
        productId: 1,
        id: "bk",
        title: "감사합니다",
        detail: "잘쓸게요",
        date: "2025. 9. 3. 오후 2:14:55",
      },
    ],
    paymentrecords: [{}, {}, {}],
  },
];
